#!/usr/bin/env python3

import argparse

import database
import merge
import suggest
import os


def print_suggestions(databasefiles, filename, line, column):
    databases = [
        database.Database.load_from_file(databasefile)
        for databasefile in databasefiles]
    merged_database = merge.merge_databases(databases)
    absfilename = os.path.abspath(filename)
    abslocation = absfilename + ':' + str(line) + ':' + str(column)
    location = filename + ':' + str(line) + ':' + str(column)

    for variable in merged_database.variables:
        if variable.location == location or variable.location == abslocation:
            print('\n'.join(suggest.suggest_for(merged_database, variable)))
            break
    else:
        raise ValueError('Variable to suggest for is not in merged database')


def main():
    parser = argparse.ArgumentParser(description='Suggest variable names')
    parser.add_argument('database', nargs='+', type=argparse.FileType('r'),
        help='JSON produced by clang-plugin containing all variables')
    parser.add_argument('filename', type=str,
        help='Filename containing variable to suggest names for')
    parser.add_argument('line', type=int,
        help='Line number of variable to suggest names for')
    parser.add_argument('column', type=int,
        help='Column number of variable to suggest names for')
    args = parser.parse_args()

    print_suggestions(args.database, args.filename, args.line, args.column)


if __name__ == '__main__':
    main()
