#!/usr/bin/env python3

import argparse


def main():
    parser = argparse.ArgumentParser(description='Suggest variable names')
    parser.add_argument('database', nargs='+', type=argparse.FileType('r'),
        help='JSON produced by clang-plugin containing all variables')
    parser.add_argument('filename', nargs=1, type=argparse.FileType('r'),
        help='Filename containing variable to suggest names for')
    parser.add_argument('line', nargs=1, type=int,
        help='Line number of variable to suggest names for')
    parser.add_argument('column', nargs=1, type=int,
        help='Column number of variable to suggest names for')
    args = parser.parse_args()

if __name__ == '__main__':
    main()
